//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int duyuruId { get; set; }
        public string duyuruBaslik { get; set; }
        public string duyuruIcerik { get; set; }
        public Nullable<System.DateTime> duyuruTarih { get; set; }
        public Nullable<int> duyuruOlusturanId { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<int> goruntuleyenBirimId { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
