//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izinler
    {
        public int izinId { get; set; }
        public Nullable<int> personelId { get; set; }
        public System.DateTime baslangicTarihi { get; set; }
        public System.DateTime bitisTarihi { get; set; }
        public Nullable<bool> onayDurumu { get; set; }
        public System.DateTime talepTarihi { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
