//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinTalepleri
    {
        public int IzinTalepId { get; set; }
        public int PersonelId { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public bool OnayDurumu { get; set; }
        public Nullable<bool> aktiflik { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
