//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Isler = new HashSet<Isler>();
            this.Loglar = new HashSet<Loglar>();
            this.Duyurular = new HashSet<Duyurular>();
            this.Mailler = new HashSet<Mailler>();
            this.Mailler1 = new HashSet<Mailler>();
            this.IzinTalepleri = new HashSet<IzinTalepleri>();
        }
    
        public int personelId { get; set; }
        public string personelAdSoyad { get; set; }
        public string personelKullaniciAd { get; set; }
        public string personelParola { get; set; }
        public Nullable<int> personelBirimId { get; set; }
        public Nullable<int> personelYetkiTurId { get; set; }
        public Nullable<bool> yeniPersonel { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<System.DateTime> personelIseGiris { get; set; }
        public Nullable<System.DateTime> personelDogumGunu { get; set; }
        public string personelMail { get; set; }
        public string personelAdres { get; set; }
        public string personelTelefon { get; set; }
        public string personelDahili { get; set; }
        public Nullable<int> personelIzın { get; set; }
        public string personelFotograf { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual YetkiTurler YetkiTurler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loglar> Loglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyurular> Duyurular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mailler> Mailler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mailler> Mailler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzinTalepleri> IzinTalepleri { get; set; }
    }
}
